// <auto-generated />
using System;
using MC_Progreso1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MC_Progreso1.Migrations
{
    [DbContext(typeof(MC_DBBContext))]
    [Migration("20230424130845_MateoCartagena")]
    partial class MateoCartagena
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MC_Progreso1.Models.MCartagena", b =>
                {
                    b.Property<int>("McID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("McID"), 1L, 1);

                    b.Property<DateTime>("McFechaHoy")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("McPromedioGlobal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("McSegundoNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("McSoltero")
                        .HasColumnType("bit");

                    b.HasKey("McID");

                    b.ToTable("MCartagena");
                });
#pragma warning restore 612, 618
        }
    }
}
